# Generated by Django 5.0.2 on 2024-02-16 06:15

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_greeting', models.IntegerField(auto_created=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jabatan', models.IntegerField(auto_created=True, unique=True)),
                ('nama_jabatan', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_project', models.IntegerField(auto_created=True, unique=True)),
                ('nama_project', models.TextField(max_length=255)),
                ('service', models.TextField(max_length=255)),
                ('nama_client', models.TextField(max_length=255)),
                ('foto_client', models.ImageField(upload_to='productionfiles/uploaded_image/client/')),
            ],
        ),
        migrations.CreateModel(
            name='PT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pt', models.IntegerField(auto_created=True, unique=True)),
                ('nama_pt', models.TextField()),
                ('logo', models.ImageField(upload_to='productionfiles/uploaded_image/logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Sejarah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sejarah', models.IntegerField(auto_created=True, unique=True)),
                ('tahun', models.DateField()),
                ('deskripsi', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sejarah', models.IntegerField(auto_created=True, unique=True)),
                ('nama_service', models.TextField(max_length=255)),
                ('deskripsi_service', django_quill.fields.QuillField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_team', models.IntegerField(auto_created=True, unique=True)),
                ('nama', models.TextField(max_length=255)),
                ('jabatan', models.TextField(max_length=255)),
                ('foto_tim', models.ImageField(upload_to='productionfiles/uploaded_image/tim/')),
            ],
        ),
        migrations.CreateModel(
            name='Tentang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tentang', models.IntegerField(auto_created=True, unique=True)),
                ('detail', models.TextField(max_length=255)),
                ('visi', models.TextField(max_length=255)),
                ('misi', django_quill.fields.QuillField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_testimoni', models.IntegerField(auto_created=True, unique=True)),
                ('nama', models.TextField(max_length=255)),
                ('deskripsi', models.TextField(max_length=255)),
            ],
        ),
    ]
