# Generated by Django 5.0.2 on 2024-02-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='teks',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
